/**
 * Données de démo pour le calendrier overlay Gr33t.
 * Portées depuis mockup-calendar-overlay.html (popoverData + focusBlocks + overtimeEvents).
 * Semaine du 6-10 avril 2026.
 */

// Base date: Monday April 6, 2026
const BASE = "2026-04-06";
const TZ = "Europe/Paris";

function dayDate(dayOffset: number): string {
  const d = new Date(2026, 3, 6 + dayOffset); // April = month 3
  return d.toISOString().split("T")[0];
}

function timeStr(dayOffset: number, hour: number): string {
  const date = dayDate(dayOffset);
  const h = Math.floor(hour);
  const m = Math.round((hour - h) * 60);
  return `${date}T${h.toString().padStart(2, "0")}:${m.toString().padStart(2, "0")}:00`;
}

// ============================================================
// Score events (all-day, showAs: free)
// ============================================================
export interface ScoreEvent {
  day: string; // "Lundi 6 avril"
  dayOffset: number;
  score: number | null;
  subject: string;
  bodyHtml: string; // generated by htmlBody.ts
}

export interface FactorRow {
  label: string;
  val: string;
  cls: "ok" | "ko" | "alert";
}

export interface Factor {
  name: string;
  summary: string;
  cls: "good" | "warn" | "bad" | "neutral";
  rows: FactorRow[];
}

export interface ScoreData {
  day: string;
  dayOffset: number;
  score: number;
  label: string;
  factors: Factor[];
}

export const scoreData: ScoreData[] = [
  {
    day: "Lundi 6 avril",
    dayOffset: 0,
    score: 75,
    label: "Suivi modéré des facteurs de récupération",
    factors: [
      {
        name: "Multi-tâche",
        summary: "0/2 réunions",
        cls: "good",
        rows: [
          { label: "10:30–11:00 Admin & fin", val: "0", cls: "ok" },
          { label: "17:00–17:45 Lecko : Réunion de suivi", val: "0", cls: "ok" },
        ],
      },
      {
        name: "Transitions",
        summary: "2/2 réunions",
        cls: "good",
        rows: [
          { label: "10:30–11:00 Admin & fin", val: "ok", cls: "ok" },
          { label: "17:00–17:45 Lecko : Réunion de suivi", val: "ok", cls: "ok" },
        ],
      },
      { name: "Débordement", summary: "aucun débordement", cls: "good", rows: [] },
      {
        name: "Plage de travail profond disponible",
        summary: "4 blocs · 9h45",
        cls: "neutral",
        rows: [
          { label: "08:00–10:30 (150 min)", val: "✓", cls: "ok" },
          { label: "11:00–12:30 (90 min)", val: "✓", cls: "ok" },
          { label: "13:30–17:00 (210 min)", val: "✓", cls: "ok" },
          { label: "17:45–20:00 (135 min)", val: "✓", cls: "ok" },
        ],
      },
    ],
  },
  {
    day: "Mardi 7 avril",
    dayOffset: 1,
    score: 50,
    label: "Suivi modéré des facteurs de récupération",
    factors: [
      {
        name: "Multi-tâche",
        summary: "0/3 réunions",
        cls: "good",
        rows: [
          { label: "09:30–10:00 Gr33Team", val: "0", cls: "ok" },
          { label: "11:00–12:00 #Gr33t - RDV Mensuel", val: "0", cls: "ok" },
          { label: "20:00–21:00 Figures of glass", val: "0", cls: "ok" },
        ],
      },
      {
        name: "Transitions",
        summary: "3/3 réunions",
        cls: "good",
        rows: [
          { label: "09:30–10:00 Gr33Team", val: "ok", cls: "ok" },
          { label: "11:00–12:00 #Gr33t - RDV Mensuel", val: "ok", cls: "ok" },
          { label: "20:00–21:00 Figures of glass", val: "ok", cls: "ok" },
        ],
      },
      {
        name: "Débordement",
        summary: "1 réunion hors plage",
        cls: "bad",
        rows: [{ label: "20:00–21:00 Figures of glass", val: "⚠", cls: "alert" }],
      },
      {
        name: "Plage de travail profond disponible",
        summary: "4 blocs · 9h30",
        cls: "neutral",
        rows: [
          { label: "08:00–09:30 (90 min)", val: "✓", cls: "ok" },
          { label: "10:00–11:00 (60 min)", val: "✓", cls: "ok" },
          { label: "12:00–12:30 (30 min)", val: "✓", cls: "ok" },
          { label: "13:30–20:00 (390 min)", val: "✓", cls: "ok" },
        ],
      },
    ],
  },
  {
    day: "Mercredi 8 avril",
    dayOffset: 2,
    score: 55,
    label: "Suivi modéré des facteurs de récupération",
    factors: [
      {
        name: "Multi-tâche",
        summary: "0/5 réunions",
        cls: "good",
        rows: [
          { label: "10:00–10:30 test", val: "0", cls: "ok" },
          { label: "10:30–11:15 Co-Biz", val: "0", cls: "ok" },
          { label: "11:15–11:30 test", val: "0", cls: "ok" },
          { label: "11:30–12:15 Comop", val: "0", cls: "ok" },
          { label: "18:30–19:15 Vincent x Arnaud", val: "0", cls: "ok" },
        ],
      },
      {
        name: "Transitions",
        summary: "1/5 réunions",
        cls: "bad",
        rows: [
          { label: "10:00–10:30 test", val: "ko", cls: "ko" },
          { label: "10:30–11:15 Co-Biz", val: "ko", cls: "ko" },
          { label: "11:15–11:30 test", val: "ko", cls: "ko" },
          { label: "11:30–12:15 Comop", val: "ko", cls: "ko" },
          { label: "18:30–19:15 Vincent x Arnaud", val: "ok", cls: "ok" },
        ],
      },
      { name: "Débordement", summary: "aucun débordement", cls: "good", rows: [] },
      {
        name: "Plage de travail profond disponible",
        summary: "4 blocs · 8h",
        cls: "neutral",
        rows: [
          { label: "08:00–10:00 (120 min)", val: "✓", cls: "ok" },
          { label: "12:15–12:30 (15 min)", val: "✓", cls: "ok" },
          { label: "13:30–18:30 (300 min)", val: "✓", cls: "ok" },
          { label: "19:15–20:00 (45 min)", val: "✓", cls: "ok" },
        ],
      },
    ],
  },
  {
    day: "Jeudi 9 avril",
    dayOffset: 3,
    score: 75,
    label: "Suivi modéré des facteurs de récupération",
    factors: [
      {
        name: "Multi-tâche",
        summary: "0/4 réunions",
        cls: "good",
        rows: [
          { label: "09:30–09:55 point d'échange", val: "0", cls: "ok" },
          { label: "14:00–16:00 Sprint Review", val: "0", cls: "ok" },
          { label: "16:20–16:45 Echange (MOUHCINE ALMI)", val: "0", cls: "ok" },
          { label: "17:00–18:00 Programme Lecko IA Augmenté", val: "0", cls: "ok" },
        ],
      },
      {
        name: "Transitions",
        summary: "4/4 réunions",
        cls: "good",
        rows: [
          { label: "09:30–09:55 point d'échange", val: "ok", cls: "ok" },
          { label: "14:00–16:00 Sprint Review", val: "ok", cls: "ok" },
          { label: "16:20–16:45 Echange (MOUHCINE ALMI)", val: "ok", cls: "ok" },
          { label: "17:00–18:00 Programme Lecko IA Augmenté", val: "ok", cls: "ok" },
        ],
      },
      { name: "Débordement", summary: "aucun débordement", cls: "good", rows: [] },
      {
        name: "Plage de travail profond disponible",
        summary: "6 blocs · 7h10",
        cls: "neutral",
        rows: [
          { label: "08:00–09:30 (90 min)", val: "✓", cls: "ok" },
          { label: "09:55–12:30 (155 min)", val: "✓", cls: "ok" },
          { label: "13:30–14:00 (30 min)", val: "✓", cls: "ok" },
          { label: "16:00–16:20 (20 min)", val: "✓", cls: "ok" },
          { label: "16:45–17:00 (15 min)", val: "✓", cls: "ok" },
          { label: "18:00–20:00 (120 min)", val: "✓", cls: "ok" },
        ],
      },
    ],
  },
];

// ============================================================
// Focus blocks (showAs: tentative)
// ============================================================
export interface FocusBlock {
  dayOffset: number;
  start: number; // decimal hour
  end: number;
  label: string;
}

export const focusBlocks: FocusBlock[] = [
  // Lundi — 4 blocs, 9h45
  { dayOffset: 0, start: 8, end: 10.5, label: "2h30" },
  { dayOffset: 0, start: 11, end: 12.5, label: "1h30" },
  { dayOffset: 0, start: 13.5, end: 17, label: "3h30" },
  { dayOffset: 0, start: 17.75, end: 20, label: "2h15" },
  // Mardi — 4 blocs, 9h30
  { dayOffset: 1, start: 8, end: 9.5, label: "1h30" },
  { dayOffset: 1, start: 10, end: 11, label: "1h" },
  { dayOffset: 1, start: 12, end: 12.5, label: "30min" },
  { dayOffset: 1, start: 13.5, end: 20, label: "6h30" },
  // Mercredi — 4 blocs, 8h
  { dayOffset: 2, start: 8, end: 10, label: "2h" },
  { dayOffset: 2, start: 12.25, end: 12.5, label: "15min" },
  { dayOffset: 2, start: 13.5, end: 18.5, label: "5h" },
  { dayOffset: 2, start: 19.25, end: 20, label: "45min" },
  // Jeudi — 6 blocs, 7h10
  { dayOffset: 3, start: 8, end: 9.5, label: "1h30" },
  { dayOffset: 3, start: 9.92, end: 12.5, label: "2h35" },
  { dayOffset: 3, start: 13.5, end: 14, label: "30min" },
  { dayOffset: 3, start: 16, end: 16.33, label: "20min" },
  { dayOffset: 3, start: 16.75, end: 17, label: "15min" },
  { dayOffset: 3, start: 18, end: 20, label: "2h" },
];

// ============================================================
// Overtime events (showAs: oof)
// ============================================================
export interface OvertimeEvent {
  dayOffset: number;
  start: number;
  end: number;
  label: string;
}

export const overtimeEvents: OvertimeEvent[] = [
  { dayOffset: 1, start: 20, end: 21, label: "Figures of glass" },
];

// ============================================================
// Helpers
// ============================================================
export function toDateTimeStr(dayOffset: number, hour: number): string {
  return timeStr(dayOffset, hour);
}

export function toDayStr(dayOffset: number): string {
  return dayDate(dayOffset);
}

export function nextDayStr(dayOffset: number): string {
  return dayDate(dayOffset + 1);
}

export const TIMEZONE = TZ;
